# Generated by Django 5.0 on 2023-12-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id_activite', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_activite', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'activite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code_client', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('type_client', models.CharField(max_length=1)),
                ('domaine_activite', models.CharField(max_length=100)),
                ('nature_activite', models.CharField(max_length=10)),
                ('raison_sociale', models.CharField(max_length=100)),
                ('chiffre_affaires', models.IntegerField()),
                ('effectifs', models.IntegerField()),
                ('commentaires_commerciaux_client', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('matricule', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nom_collaborateur', models.CharField(max_length=20)),
                ('prenom_collaborateur', models.CharField(max_length=20)),
                ('sexe_collaborateur', models.CharField(max_length=1)),
                ('etat_civil_collaborateur', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'collaborateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_contact', models.AutoField(primary_key=True, serialize=False)),
                ('nom_contact', models.CharField(max_length=20)),
                ('prenom_contact', models.CharField(max_length=20)),
                ('email_contact', models.CharField(max_length=50)),
                ('tel_contact', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id_contrat', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut_contrat', models.DateField()),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('libelle_contrat', models.CharField(blank=True, max_length=50, null=True)),
                ('salaire', models.DecimalField(decimal_places=4, max_digits=19)),
                ('type', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'contrat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('titre_document', models.CharField(max_length=100)),
                ('resume_document', models.CharField(max_length=1000)),
                ('date_diffusion_document', models.DateField()),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('num_lot', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('charge_estimee', models.SmallIntegerField()),
                ('charge_reelle_prod', models.SmallIntegerField(blank=True, null=True)),
                ('charge_reelle_validation', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'etape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id_fonction', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_fonction', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fonction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id_intervention', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut_intervention', models.DateField()),
                ('date_fin_intervention', models.DateField()),
                ('libelle_intervention', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'intervention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('code_projet', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('libelle_long_projet', models.CharField(max_length=50)),
                ('libelle_court_projet', models.CharField(max_length=10)),
                ('type_projet', models.CharField(max_length=1)),
                ('cycle_vie_projet', models.CharField(max_length=10)),
                ('infos_techniques_projet', models.CharField(max_length=100)),
                ('charge_estimee_projet', models.SmallIntegerField()),
                ('remarques_estimation_projet', models.CharField(max_length=100)),
                ('date_debut_prevue', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_debut_reelle', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('equipe_max_projet', models.SmallIntegerField()),
                ('commentaires_commerciaux_projet', models.CharField(blank=True, max_length=255, null=True)),
                ('secteur_activite', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'projet',
                'managed': False,
            },
        ),
    ]
